// One-time generator: projects world-atlas countries (110m) with d3-geo and
// writes a static TS module of SVG paths. Keeps heavy geo deps OUT of the app
// bundle — the app only imports the generated file.
//
//   node scripts/gen-world.mjs
//
// Source data: world-atlas (Natural Earth, public domain). topojson-client + d3-geo (BSD).

import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoNaturalEarth1, geoPath, geoCentroid } from "d3-geo";

const W = 1000;
const H = 500;

const topo = JSON.parse(readFileSync("node_modules/world-atlas/countries-110m.json", "utf8"));
const fc = feature(topo, topo.objects.countries);

// Drop Antarctica (id 010) — big empty bottom blob, hurts the composition.
fc.features = fc.features.filter((f) => String(f.id) !== "10" && f.properties?.name !== "Antarctica");

const projection = geoNaturalEarth1().fitSize([W, H], fc);
const path = geoPath(projection);

const round = (s) => s.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));

const countries = [];
for (const f of fc.features) {
  const d = path(f);
  if (!d) continue;
  const c = path.centroid(f);
  const ll = geoCentroid(f);
  if (!isFinite(c[0]) || !isFinite(c[1])) continue;
  countries.push({
    id: String(f.id),
    name: f.properties?.name ?? "",
    d: round(d),
    cx: Number(c[0].toFixed(1)),
    cy: Number(c[1].toFixed(1)),
    lon: Number(ll[0].toFixed(2)),
    lat: Number(ll[1].toFixed(2))
  });
}

const header = `// AUTO-GENERATED by scripts/gen-world.mjs — do not edit by hand.
// World country polygons (Natural Earth 110m via world-atlas, public domain),
// projected with d3-geo geoNaturalEarth1 into a ${W}x${H} viewBox.

export const WORLD_VIEW = { w: ${W}, h: ${H} } as const;

export type GeoCountry = {
  id: string;
  name: string;
  d: string;
  cx: number;
  cy: number;
  lon: number;
  lat: number;
};

export const WORLD_COUNTRIES: GeoCountry[] = ${JSON.stringify(countries)};
`;

writeFileSync("src/data/world-countries.generated.ts", header);
console.log(`Wrote ${countries.length} countries -> src/data/world-countries.generated.ts`);
